name: Build Qt Project

on: push

jobs:
  build:
    name: Build Qt Project
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0 libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-image0 libxcb-render-util0 libxcb-xfixes0 libxkbcommon-x11-0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          modules: 'qtmultimedia'

      - name: Add Qt to PATH
        run: echo "$HOME/Qt/6.7.0/gcc_64/bin" >> $GITHUB_PATH

      - name: Create build directory
        run: mkdir build2

      - name: Build project
        run: |
          cd build2
          export PATH="$HOME/Qt/6.7.0/gcc_64/bin:$PATH"
          qmake ../finalqmakeproject.pro  # Replace with your actual .pro file name
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build2-artifacts
          path: build2/
